// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkmcjmuyqqydknhfecvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbWNqbXV5cXF5ZGtuaGZlY3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzMwNjIsImV4cCI6MjA2MjYwOTA2Mn0.LhJZQaezv-R-91ptICsDO7FJ1nBiUi3lu8QVJh8gWQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);