
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkmcjmuyqqydknhfecvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbWNqbXV5cXF5ZGtuaGZlY3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzMwNjIsImV4cCI6MjA2MjYwOTA2Mn0.LhJZQaezv-R-91ptICsDO7FJ1nBiUi3lu8QVJh8gWQw";

// Configure the Supabase client with storage and auth options
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// API configuration
export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// Helper function to get API headers with auth token
export const getAuthHeaders = async () => {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  
  return {
    'Content-Type': 'application/json',
    'Authorization': token ? `Bearer ${token}` : '',
  };
};
